# Generated by Django 5.2.7 on 2025-10-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Name',
            new_name='name',
        ),
    ]
